settings:
  title: 'Status | Level Crush'
  url: 'https://status.levelcrush.com' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 7 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: games.levelcrush # unique identifier
    name: games.levelcrush.com
    description: 'Where we host our game servers' # default=empty
    url: 'https://games.levelcrush.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: spt.levelcrush # unique identifier
    name: spt.levelcrush.com
    description: 'Level Crush SPT Server' # default=empty
    url: 'https://spt.levelcrush.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: tabletop.levelcrush # unique identifier
    name: tabletop.levelcrush.com
    description: 'Online DnD for the homies' # default=empty
    url: 'https://tabletop.levelcrush.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: auth.levelcrush # unique identifier
    name: auth.levelcrush.com
    description: 'Login to the Level Crush network' # default=empty
    url: 'https://auth.levelcrush.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: code.levelcrush # unique identifier
    name: code.levelcrush.com
    description: 'Codehub for all things Level Crush' # default=empty
    url: 'https://code.levelcrush.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: vault.levelcrush # unique identifier
    name: vault.levelcrush.com
    description: 'Securely Managed Passwords' # default=empty
    url: 'https://vault.levelcrush.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: assets.levelcrush # unique identifier
    name: assets.levelcrush.com
    description: 'Our Asset Server' # default=empty
    url: 'https://assets.levelcrush.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
