settings:
  title: Status | Level Crush
  url: https://status.levelcrush.com
  logo: logo.png
  daysInHistogram: 30
  collectResponseTimes: true
  allmonitorsOperational: All Systems Operational
  notAllmonitorsOperational: Not All Systems Operational
  monitorLabelOperational: Operational
  monitorLabelNotOperational: Not Operational
  monitorLabelNoData: No data
  dayInHistogramNoData: No data
  dayInHistogramOperational: All good
  dayInHistogramNotOperational: " incident(s)"
monitors:
  - id: levelcrush
    name: Website
    description: Our main homepage
    url: https://levelcrush.com
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: store.levelcrush
    name: Store
    description: Our Level Crush Store. For now hosted on a subdomain
    url: https://store.levelcrush.com
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: games.levelcrush
    name: games.levelcrush.com
    description: Where we host our game servers
    url: https://games.levelcrush.com
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
  - id: spt.levelcrush
    name: spt.levelcrush.com
    description: Level Crush SPT Server
    url: https://spt.levelcrush.com/
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
  - id: tabletop.levelcrush
    name: tabletop.levelcrush.com
    description: Online DnD for the homies
    url: https://tabletop.levelcrush.com/
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: auth.levelcrush
    name: auth.levelcrush.com
    description: Login to the Level Crush network
    url: https://auth.levelcrush.com/
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: code.levelcrush
    name: code.levelcrush.com
    description: Codehub for all things Level Crush
    url: https://code.levelcrush.com/
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: vault.levelcrush
    name: vault.levelcrush.com
    description: Securely Managed Passwords
    url: https://vault.levelcrush.com/
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: assets.levelcrush
    name: assets.levelcrush.com
    description: Our Asset Server
    url: https://assets.levelcrush.com
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
